import Vue from 'vue';

import { Search, Button, Swipe, SwipeItem, Grid, GridItem, Icon, Tag, Toast, DropdownMenu, DropdownItem, Image as VanImage, List, Cell, Empty, Tabbar, TabbarItem, Card, Pagination, Form, Field, Tab, Tabs,Col, Row, GoodsAction,GoodsActionIcon, GoodsActionButton,Stepper,Checkbox, CheckboxGroup,SubmitBar,SwipeCell  } from 'vant';

Vue.use(Search);
Vue.use(Button);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(Grid);
Vue.use(GridItem);
Vue.use(Icon);
Vue.use(Tag);
Vue.use(Toast);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(VanImage);
Vue.use(List);
Vue.use(Cell);
Vue.use(Empty);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Card);
Vue.use(Pagination);
Vue.use(Form);
Vue.use(Field);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Col);
Vue.use(Row);
Vue.use(GoodsAction);
Vue.use(GoodsActionButton);
Vue.use(GoodsActionIcon);
Vue.use(Stepper);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(SubmitBar);
Vue.use(SwipeCell);